//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoekenAuteursEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public string ISBN { get; set; }
        public string Titel { get; set; }
        public int AuthorID { get; set; }
        public int Pages { get; set; }
        public string Genre { get; set; }
        public string Content { get; set; }
    
        public virtual Authors Authors { get; set; }
    }
}
