//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoekenAuteursEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferences
    {
        public int UserID { get; set; }
        public int AuthorID { get; set; }
        public Nullable<System.DateTime> PreferenceData { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Users Users { get; set; }
    }
}
